# Generated by Django 2.1.7 on 2019-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='spider_detail_Common',
            field=models.CharField(max_length=3000),
        ),
    ]
