# Generated by Django 2.1.7 on 2019-03-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0002_auto_20190310_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyse_id', models.CharField(max_length=50)),
                ('analyse_positive_prob', models.TextField()),
                ('analyse_negative_prob', models.TextField()),
                ('analyse_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
