# Generated by Django 2.1.7 on 2019-04-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0003_analyse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taobao_id', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
